import type { StructuredMemoryService } from "../../memory/structured-memory/service.js";
import type {
  CreateEntityInput,
  EntityType,
  UpdateEntityPatch,
} from "../../memory/structured-memory/types.js";
import { ENTITY_TYPES } from "../../memory/structured-memory/types.js";
import type { Tool, ToolResult } from "../tool-types.js";

function parseJsonArg<T>(raw: unknown, field: string): T | undefined {
  if (raw === undefined || raw === null || raw === "") return undefined;
  if (typeof raw !== "string") {
    throw new Error(`${field} must be a JSON-encoded string`);
  }
  try {
    return JSON.parse(raw) as T;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new Error(`${field} is not valid JSON: ${msg}`);
  }
}

function asString(v: unknown): string | undefined {
  return typeof v === "string" && v.trim() !== "" ? v : undefined;
}

function errorResult(message: string): ToolResult {
  return { success: false, data: null, error: message };
}

export function createStructuredMemoryTool(
  service: StructuredMemoryService,
): Tool {
  return {
    definition: {
      name: "structured_memory",
      description:
        "Manage structured knowledge about people, projects, groups, contexts and preferences. " +
        "Use this when the user references recurring people, relations between them, or stable contexts — " +
        "complements save_memory/search_memories with a graph-like layer. " +
        "Actions: " +
        "create_entity (new entity with aliases/tags), " +
        "update_entity (add aliases/tags/notes), " +
        "search_entities (by name or alias), " +
        "get_entity (single entity), " +
        "get_profile (entity + relations + linked memories), " +
        "create_relation (link two entities, e.g. spouse_of, mother_in_law_of, member_of), " +
        "delete_relation, " +
        "suggest_duplicates (candidates with score and reasons), " +
        "link_memory (attach an existing memory by key), " +
        "merge_entities (requires confirm=true — combine aliases, redirect relations, delete secondary). " +
        "Array/object fields (aliases, attributes, notes, tags) must be passed as JSON-encoded strings. " +
        "Reuse memory libre via link_memory; do not duplicate free memories as entity notes.",
      parameters: {
        type: "object",
        properties: {
          action: {
            type: "string",
            description: "The operation to perform",
            enum: [
              "create_entity",
              "update_entity",
              "search_entities",
              "get_entity",
              "get_profile",
              "create_relation",
              "delete_relation",
              "suggest_duplicates",
              "link_memory",
              "merge_entities",
            ],
          },
          entity_type: {
            type: "string",
            description:
              "Type of entity. Required for create_entity. Optional filter for search_entities.",
            enum: [...ENTITY_TYPES],
          },
          canonical_name: {
            type: "string",
            description:
              "Full canonical name of the entity (e.g. 'Marilú Lozano'). Required for create_entity.",
          },
          slug: {
            type: "string",
            description:
              "Stable lowercase identifier (e.g. 'marilu_lozano'). Autogenerated from canonical_name if omitted. Usable as entity_id alternative for get_entity, get_profile, create_relation, link_memory, merge_entities.",
          },
          entity_id: {
            type: "string",
            description:
              "UUID of an entity. Alternative to slug for get_entity, update_entity, get_profile, suggest_duplicates, merge_entities.",
          },
          aliases: {
            type: "string",
            description:
              'JSON-encoded array of alias strings. For create_entity initial list, for update_entity use aliases_add/aliases_remove instead. Example: \'["Marilú","Suegra"]\'',
          },
          aliases_add: {
            type: "string",
            description:
              "JSON-encoded array of aliases to add on update_entity.",
          },
          aliases_remove: {
            type: "string",
            description:
              "JSON-encoded array of aliases to remove on update_entity.",
          },
          attributes: {
            type: "string",
            description:
              'JSON-encoded object with free-form attributes (e.g. \'{"familyRole":"mother_in_law"}\').',
          },
          notes: {
            type: "string",
            description:
              'JSON-encoded array of notes (create_entity / create_relation). Example: \'["Aparece en el balance familiar"]\'',
          },
          notes_add: {
            type: "string",
            description:
              "JSON-encoded array of notes to append on update_entity.",
          },
          tags: {
            type: "string",
            description:
              'JSON-encoded array of tags (create_entity). Example: \'["familia","balance"]\'',
          },
          tags_add: {
            type: "string",
            description:
              "JSON-encoded array of tags to add on update_entity.",
          },
          tags_remove: {
            type: "string",
            description:
              "JSON-encoded array of tags to remove on update_entity.",
          },
          confidence: {
            type: "string",
            description:
              "Optional confidence level when saving an entity or relation.",
            enum: ["high", "medium", "low"],
          },
          query: {
            type: "string",
            description:
              "Search query for search_entities. Matches canonical_name and aliases (case-insensitive).",
          },
          limit: {
            type: "string",
            description: "Max results for search_entities. Default 10.",
          },
          from_slug: {
            type: "string",
            description:
              "Slug of the origin entity for create_relation. Alternative to from_id.",
          },
          from_id: {
            type: "string",
            description:
              "UUID of the origin entity for create_relation. Alternative to from_slug.",
          },
          to_slug: {
            type: "string",
            description:
              "Slug of the target entity for create_relation. Alternative to to_id.",
          },
          to_id: {
            type: "string",
            description:
              "UUID of the target entity for create_relation. Alternative to to_slug.",
          },
          relation_type: {
            type: "string",
            description:
              "Relation verb for create_relation (e.g. spouse_of, mother_in_law_of, sibling_of, member_of, reviewer_of, owner_of, related_to, participant_in).",
          },
          relation_id: {
            type: "string",
            description: "UUID of the relation to delete_relation.",
          },
          memory_key: {
            type: "string",
            description:
              "Key of an existing memory (from save_memory) to link into the entity's sourceMemoryIds. For link_memory.",
          },
          primary_id: {
            type: "string",
            description:
              "For merge_entities: id or slug of the PRIMARY entity (surviving).",
          },
          secondary_id: {
            type: "string",
            description:
              "For merge_entities: id or slug of the SECONDARY entity (will be deleted after merge).",
          },
          confirm: {
            type: "string",
            description:
              "Set to 'true' to confirm destructive operations like merge_entities. Without this, merge_entities refuses.",
            enum: ["true", "false"],
          },
          force: {
            type: "string",
            description:
              "For create_entity: set to 'true' to create even when duplicate candidates are detected.",
            enum: ["true", "false"],
          },
          regenerate_slug: {
            type: "string",
            description:
              "For update_entity: set to 'true' (combined with canonical_name) to regenerate the slug from the new name.",
            enum: ["true", "false"],
          },
        },
        required: ["action"],
      },
    },

    async execute(args, context): Promise<ToolResult> {
      const action = typeof args.action === "string" ? args.action : "";
      const userId = context.userId;

      try {
        switch (action) {
          case "create_entity": {
            const entityType = asString(args.entity_type) as
              | EntityType
              | undefined;
            const canonicalName = asString(args.canonical_name);
            if (!entityType) return errorResult("entity_type is required");
            if (!canonicalName)
              return errorResult("canonical_name is required");

            const input: CreateEntityInput = {
              entityType,
              canonicalName,
              slug: asString(args.slug),
              aliases: parseJsonArg<string[]>(args.aliases, "aliases") ?? [],
              attributes:
                parseJsonArg<Record<string, unknown>>(
                  args.attributes,
                  "attributes",
                ) ?? {},
              notes: parseJsonArg<string[]>(args.notes, "notes") ?? [],
              tags: parseJsonArg<string[]>(args.tags, "tags") ?? [],
              confidence: asString(args.confidence) as
                | "high"
                | "medium"
                | "low"
                | undefined,
              force: asString(args.force) === "true",
            };

            const result = service.createEntity(userId, input);
            if (!result.created) {
              return {
                success: false,
                data: { duplicates: result.duplicates },
                error:
                  "Potential duplicate(s) detected. Review candidates and either use a different canonical_name, merge into an existing entity, or re-call with force='true' to create anyway.",
              };
            }
            return { success: true, data: { entity: result.entity } };
          }

          case "update_entity": {
            const idOrSlug = asString(args.entity_id) ?? asString(args.slug);
            if (!idOrSlug)
              return errorResult("entity_id or slug is required");

            const patch: UpdateEntityPatch = {
              canonicalName: asString(args.canonical_name),
              entityType: asString(args.entity_type) as EntityType | undefined,
              aliasesAdd: parseJsonArg<string[]>(
                args.aliases_add,
                "aliases_add",
              ),
              aliasesRemove: parseJsonArg<string[]>(
                args.aliases_remove,
                "aliases_remove",
              ),
              attributes: parseJsonArg<Record<string, unknown>>(
                args.attributes,
                "attributes",
              ),
              notesAdd: parseJsonArg<string[]>(args.notes_add, "notes_add"),
              tagsAdd: parseJsonArg<string[]>(args.tags_add, "tags_add"),
              tagsRemove: parseJsonArg<string[]>(
                args.tags_remove,
                "tags_remove",
              ),
              confidence: asString(args.confidence) as
                | "high"
                | "medium"
                | "low"
                | undefined,
              regenerateSlug: asString(args.regenerate_slug) === "true",
            };

            const updated = service.updateEntity(userId, idOrSlug, patch);
            return { success: true, data: { entity: updated } };
          }

          case "search_entities": {
            const query = asString(args.query);
            if (!query) return errorResult("query is required");
            const entityType = asString(args.entity_type) as
              | EntityType
              | undefined;
            const limitStr = asString(args.limit);
            const limit = limitStr ? Math.max(1, parseInt(limitStr, 10) || 10) : 10;
            const entities = service.searchEntities(userId, query, {
              type: entityType,
              limit,
            });
            return {
              success: true,
              data: {
                count: entities.length,
                entities: entities.map((e) => ({
                  id: e.id,
                  slug: e.slug,
                  canonicalName: e.canonicalName,
                  entityType: e.entityType,
                  aliases: e.aliases,
                  tags: e.tags,
                })),
              },
            };
          }

          case "get_entity": {
            const idOrSlug = asString(args.entity_id) ?? asString(args.slug);
            if (!idOrSlug)
              return errorResult("entity_id or slug is required");
            const entity = service.getEntity(userId, idOrSlug);
            if (!entity)
              return errorResult(`Entity not found: ${idOrSlug}`);
            return { success: true, data: { entity } };
          }

          case "get_profile": {
            const idOrSlug = asString(args.entity_id) ?? asString(args.slug);
            if (!idOrSlug)
              return errorResult("entity_id or slug is required");
            const profile = service.getProfile(userId, idOrSlug);
            if (!profile)
              return errorResult(`Entity not found: ${idOrSlug}`);
            return { success: true, data: profile };
          }

          case "create_relation": {
            const relationType = asString(args.relation_type);
            if (!relationType)
              return errorResult("relation_type is required");
            const fromSlug = asString(args.from_slug);
            const fromId = asString(args.from_id);
            const toSlug = asString(args.to_slug);
            const toId = asString(args.to_id);
            if (!fromSlug && !fromId)
              return errorResult("from_slug or from_id is required");
            if (!toSlug && !toId)
              return errorResult("to_slug or to_id is required");

            const relation = service.createRelation(userId, {
              fromSlug,
              fromId,
              toSlug,
              toId,
              relationType,
              attributes:
                parseJsonArg<Record<string, unknown>>(
                  args.attributes,
                  "attributes",
                ) ?? {},
              notes: parseJsonArg<string[]>(args.notes, "notes") ?? [],
              confidence: asString(args.confidence) as
                | "high"
                | "medium"
                | "low"
                | undefined,
            });
            return { success: true, data: { relation } };
          }

          case "delete_relation": {
            const relationId = asString(args.relation_id);
            if (!relationId) return errorResult("relation_id is required");
            const deleted = service.deleteRelation(userId, relationId);
            if (!deleted)
              return errorResult(`Relation not found: ${relationId}`);
            return { success: true, data: { deleted: relationId } };
          }

          case "suggest_duplicates": {
            const idOrSlug = asString(args.entity_id) ?? asString(args.slug);
            if (!idOrSlug)
              return errorResult("entity_id or slug is required");
            const duplicates = service.suggestDuplicates(userId, idOrSlug);
            return {
              success: true,
              data: { count: duplicates.length, duplicates },
            };
          }

          case "link_memory": {
            const idOrSlug = asString(args.entity_id) ?? asString(args.slug);
            const memoryKey = asString(args.memory_key);
            if (!idOrSlug)
              return errorResult("entity_id or slug is required");
            if (!memoryKey) return errorResult("memory_key is required");
            const result = service.linkMemory(userId, idOrSlug, memoryKey);
            return {
              success: true,
              data: {
                entityId: result.entity.id,
                entitySlug: result.entity.slug,
                memoryId: result.memoryId,
              },
            };
          }

          case "merge_entities": {
            const primary = asString(args.primary_id);
            const secondary = asString(args.secondary_id);
            if (!primary) return errorResult("primary_id is required");
            if (!secondary) return errorResult("secondary_id is required");
            const confirm = asString(args.confirm) === "true";
            const result = service.mergeEntities(
              userId,
              primary,
              secondary,
              { confirm },
            );
            return {
              success: true,
              data: { merged: result.merged, log: result.log },
            };
          }

          default:
            return errorResult(
              `Unknown action: ${action}. Valid: create_entity, update_entity, search_entities, get_entity, get_profile, create_relation, delete_relation, suggest_duplicates, link_memory, merge_entities`,
            );
        }
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        return { success: false, data: null, error: message };
      }
    },
  };
}
